name: 'Github Logs to Elastic Search'
description: 'Send Github Action logs to Elastic Search'
author: 'KnutFr'
branding:
  icon: database
  color: red
inputs:
  githubToken:
    required: true
    description: "GitHub PAT"
  githubOrg:
    required: true
    description: "The github organization to read the workflows logs from"
  githubRepository:
    required: true
    description: "The github repository to read the workflows logs from"
  githubRunId:
    required: true
    description: "The workflow specific run id to read the logs from"
  elasticApiKeyId:
    required: false
    description: "Elastic api key id"
  elasticApiKey:
    required: false
    description: "Elastic api key"
  elasticHost:
    required: true
    description: "The elastic host"
  elasticIndex:
    required: true
    description: "The elastic index"
  elasticCloudId:
    required: false
    description: "The elastic index"
  elasticCloudUser:
    required: false
    description: "The elastic index"
  elasticCloudPassword:
    required: false
    description: "The elastic index"
  totalTests:
    required: false
    description: 'Total number of tests executed in the workflow'
  passedTests:
    required: false
    description: 'Number of successfully passed tests'
  failedTests:
    required: false
    description: 'Number of failed tests'
runs:
  using: 'node12'
  main: 'dist/index.js'
